tasks:
  - init: echo 'init script' # runs during prebuild
    command: echo 'start script'

jetbrains:
  intellij:
    prebuilds:
      version: both
  rider:
    prebuilds:
      version: both
  clion:
    prebuilds:
      version: both
