tasks:
  - command: echo 'command script 3' # runs during prebuild
    init: |
      echo 'start init 14'
      sleep 40
      cat /tmp/backend-latest/bin/idea.properties
      echo 'end init'

jetbrains:
  intellij:
    prebuilds:
      version: latest
