tasks:
  - init: echo 'init script 2'
    command: echo 'start script'

jetbrains:
  intellij:
    prebuilds:
      version: stable
  phpstorm:
    prebuilds:
      version: latest
  goland:
    prebuilds:
      version: both

