tasks:
  - init: echo 'init script' # runs during prebuild
    command: |
      echo 'start script 12'
      sleep 5
      cat /tmp/backend/bin/idea.properties

jetbrains:
  intellij:
    prebuilds:
      version: latest
