tasks:
  - init: echo 'init script' # runs during prebuild
    command: echo 'start script'

jetbrains:
  intellij:
    prebuilds:
      version: stable
  rider:
    prebuilds:
      version: latest
  goland:
    prebuilds:
      version: both

