tasks:
  - command: echo 'command script' # runs during prebuild
    init: |
      echo 'start init 13'
      sleep 5
      cat /tmp/backend/bin/idea.properties

jetbrains:
  intellij:
    prebuilds:
      version: latest
