tasks:
  - init: echo 'init script' # runs during prebuild
    command: |
      echo 'start script 10'
      sleep 5
      cat /tmp/backend/bin/idea.properties

jetbrains:
  intellij:
    prebuilds:
      version: both
  pycharm:
    prebuilds:
      version: both
  phpstorm:
    prebuilds:
      version: both
  goland:
    prebuilds:
      version: both
  webstorm:
    prebuilds:
      version: both            
  rubymine:
    prebuilds:
      version: both            
  rider:
    prebuilds:
      version: both
