tasks:
  - command: echo 'command script 1' # runs during prebuild
    init: |
      echo 'start init 14'
      cat /tmp/backend-latest/bin/idea.properties

jetbrains:
  intellij:
    prebuilds:
      version: latest
